### ISSUE TITLE
oVirt 4.4 support?

### ISSUE THREAD

**Issue by GervaisdeM** [myoung34/vagrant-ovirt4#119]
I'm trying to get this working with the current version of oVirt (4.4.2.6) and am receiving a 404 error. I see that the Gemfile.lock specifies ovirt-engine-sdk (4.0.12) and wonder why I am getting the error that I am seeing.

```
==> default: An error occured. Recovering..
==> default: Halting VM...
==> default: Waiting for VM to shutdown...
==> default: Removing VM...
Traceback (most recent call last):
	32: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	31: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:201:in `action'
	30: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:201:in `call'
	29: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:613:in `lock'
	28: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:215:in `block in action'
	27: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:243:in `action_raw'
	26: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	25: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	24: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	23: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	22: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	21: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	20: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	19: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	18: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	17: from /Users/gervais/.vagrant.d/gems/2.6.6/gems/vagrant-ovirt4-1.2.3/lib/vagrant-ovirt4/action/connect_ovirt.rb:32:in `call'
	16: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	15: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
	14: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	13: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	12: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	11: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	10: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 9: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 8: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 7: from /Users/gervais/.vagrant.d/gems/2.6.6/gems/vagrant-ovirt4-1.2.3/lib/vagrant-ovirt4/action/set_name_of_domain.rb:17:in `call'
	 6: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 5: from /Users/gervais/.vagrant.d/gems/2.6.6/gems/vagrant-ovirt4-1.2.3/lib/vagrant-ovirt4/action/create_vm.rb:125:in `call'
	 4: from /Users/gervais/.vagrant.d/gems/2.6.6/gems/vagrant-ovirt4-1.2.3/lib/vagrant-ovirt4/action/create_vm.rb:125:in `each'
	 3: from /Users/gervais/.vagrant.d/gems/2.6.6/gems/vagrant-ovirt4-1.2.3/lib/vagrant-ovirt4/action/create_vm.rb:126:in `block in call'
	 2: from /Users/gervais/.vagrant.d/gems/2.6.6/gems/ovirt-engine-sdk-4.0.12/lib/ovirtsdk4/services.rb:6721:in `add'
	 1: from /Users/gervais/.vagrant.d/gems/2.6.6/gems/ovirt-engine-sdk-4.0.12/lib/ovirtsdk4/service.rb:65:in `check_fault'
/Users/gervais/.vagrant.d/gems/2.6.6/gems/ovirt-engine-sdk-4.0.12/lib/ovirtsdk4/service.rb:52:in `raise_error': HTTP response code is 404. (OvirtSDK4::Error)
```

Any help would be appreciated.

**Comment by GervaisdeM** [comment]
I had an issue with my Vagrantfile.
It is now hanging at "==> default: Waiting for VM to get an IP address..."
But I believe this is likely either config or another issue on my end.
