### ISSUE TITLE
Exception on up for non-unique 'name'

### ISSUE THREAD

**Issue by myoung34** [myoung34/vagrant-ovirt4#35]
``` marcyoung  ~  repos  github  vagrant-ovirt4  vagrant up
Ignoring ovirt-engine-sdk-4.0.7 because its extensions are not built.  Try: gem pristine ovirt-engine-sdk --version 4.0.7
Bringing machine 'default' up with 'ovirt4' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:          foo
==> default:  -- Cluster:       Default
==> default:  -- Template:      Vagrant-Centos7-test
==> default:  -- Console Type:  vnc
==> default: An error occured. Recovering..
==> default: VM is not created. Please run `vagrant up` first.
/Users/marcyoung/.vagrant.d/gems/2.2.5/gems/ovirt-engine-sdk-4.0.7/lib/ovirtsdk4/service.rb:52:in `raise_error': Fault reason is "Operation Failed". Fault detail is "[Cannot add VM. The VM name is already in use, please choose a unique name and try again.]". HTTP response code is 409. (OvirtSDK4::Error)
        from /Users/marcyoung/.vagrant.d/gems/2.2.5/gems/ovirt-engine-sdk-4.0.7/lib/ovirtsdk4/service.rb:67:in `check_fault'
        from /Users/marcyoung/.vagrant.d/gems/2.2.5/gems/ovirt-engine-sdk-4.0.7/lib/ovirtsdk4/services.rb:30809:in `add'
        from /Users/marcyoung/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-0.0.1/lib/vagrant-ovirt4/action/create_vm.rb:43:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /Users/marcyoung/.vagrant.d/gems/2.2.5/gems/vagrant-ovirt4-0.0.1/lib/vagrant-ovirt4/action/connect_ovirt.rb:31:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'```

**Comment by myoung34** [comment]
Still an issue
